import { type NextPage } from "next";
import Head from "next/head";

import AuthBar from "../components/User/AuthBar";
import LinkAdd from "../components/Links/Add";
import LinkList from "../components/Links/UserList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthBar />
      <main className="min-h-screen bg-slate-800">
        <div className="container m-auto px-4 py-16">
          <h1 className="m-8 text-center text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">Shory</h1>
          <LinkAdd />
          <LinkList />
        </div>
      </main>
    </>
  );
};

export default Home;
